//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod mrbs_area;
pub mod mrbs_entry;
pub mod mrbs_participants;
pub mod mrbs_repeat;
pub mod mrbs_room;
pub mod mrbs_sessions;
pub mod mrbs_variables;
pub mod mrbs_zoneinfo;
pub mod users;
