//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mrbs_zoneinfo")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub timezone: String,
    pub outlook_compatible: u8,
    #[sea_orm(column_type = "Text", nullable)]
    pub vtimezone: Option<String>,
    pub last_updated: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
