//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mrbs_repeat")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub start_time: i32,
    pub end_time: i32,
    pub rep_type: i32,
    pub end_date: i32,
    pub rep_opt: String,
    pub room_id: i32,
    pub timestamp: Option<DateTimeUtc>,
    pub create_by: String,
    pub modified_by: String,
    pub name: String,
    pub r#type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub rep_interval: i16,
    pub month_absolute: Option<i16>,
    pub month_relative: Option<String>,
    pub status: u8,
    pub reminded: Option<i32>,
    pub info_time: Option<i32>,
    pub info_user: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub info_text: Option<String>,
    pub ical_uid: String,
    pub ical_sequence: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mrbs_entry::Entity")]
    MrbsEntry,
    #[sea_orm(
        belongs_to = "super::mrbs_room::Entity",
        from = "Column::RoomId",
        to = "super::mrbs_room::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    MrbsRoom,
}

impl Related<super::mrbs_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MrbsEntry.def()
    }
}

impl Related<super::mrbs_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MrbsRoom.def()
    }
}
