//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::mrbs_area::Entity as MrbsArea;
pub use super::mrbs_entry::Entity as MrbsEntry;
pub use super::mrbs_participants::Entity as MrbsParticipants;
pub use super::mrbs_repeat::Entity as MrbsRepeat;
pub use super::mrbs_room::Entity as MrbsRoom;
pub use super::o_auth2_sessions::Entity as OAuth2Sessions;
pub use super::users::Entity as Users;
