version: "3.9"

services:
  app:
    build: ../
    container_name: workspace_booking_app
    depends_on:
      - db
    environment:
      # SeaORM connection URL
      DATABASE_URL: mysql://worker:worker@db:3306/mrbs
    ports:
      - "5150:5150"
    command: []
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootworker
      MYSQL_DATABASE: mrbs
      MYSQL_USER: worker
      MYSQL_PASSWORD: worker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: