[env]
DATABASE_URL="mysql://devuser:devuser@localhost:3320/mrbs"
#OAUTH_CLIENT_ID="workspace-booking"
#OAUTH_CLIENT_SECRET="2shYGe1OXfO2wBDJA5OD6dB29U8UVdWhHzp4N4xFiqilQ9y7Z4HzUEHXaTBWbOTV9b3HeiNk1IGHghi1f1tkr8oGmR2HexUUnDPIWtZQiMHrAkPehtRC3B84UdMaUizT"
#AUTH_URL="http://localhost:9000/application/o/authorize/"
#TOKEN_URL="http://localhost:9000/application/o/token/"
#REDIRECT_URL="http://localhost:5150/api/oauth2/authentik/callback/cookie"
#PROFILE_URL="http://localhost:9000/application/o/userinfo/"
##PROTECTED_URL="http://localhost:5150/"
##AUTH_TYPE="request_body"
RUST_LOG="loco_oauth2=debug,workspace_booking_system=debug,cookie=debug"
OAUTH_CLIENT_ID="qSpCQZRkAbR9VCxTI6mXHOuHH23U3hpXaeqKXxg0"
OAUTH_CLIENT_SECRET="WIlwGRUS8eVM80DYxQe45MKTQVJO3VecYXtgs7FnYkqrTQtFIzZYQw0BWKlToOVGyGXY36uh7H2FB8edZn4gG02dRYIbTZFqMaAxHiJ2qYQpGNf9WRQb0qMd14EVM3kj"
AUTH_URL="https://sso.verbis.dkfz.de/application/o/authorize/"
TOKEN_URL="https://sso.verbis.dkfz.de/application/o/token/"
REDIRECT_URL="http://localhost:5150/api/oauth2/authentik/callback/cookie"
PROFILE_URL="https://sso.verbis.dkfz.de/application/o/userinfo/"
PROTECTED_URL="http://localhost:5150/"
##AUTH_TYPE="request_body"
##RUST_LOG="loco_oauth2=debug,workspace_booking_system=debug,cookie=debug"
##RUST_LOG="reqwest=trace,loco_oauth2=debug,workspace_booking_system=debug"
[alias]
loco = "run --"
loco-tool = "run --"

playground = "run --example playground"
