# Loco configuration file documentation

# Application logging configuration
logger:
  # Enable or disable logging.
  enable: true
  # Enable pretty backtrace (sets RUST_BACKTRACE=1)
  pretty_backtrace: false
  # Log level, options: trace, debug, info, warn or error.
  level: info
  # Define the logging format. options: compact, pretty or json
  format: compact
  # By default the logger has filtering only logs that came from your code or logs that came from `loco` framework. to see all third party libraries
  # Uncomment the line below to override to see all third party libraries you can enable this config and override the logger filters.
  # override_filter: trace

# Web server configuration
server:
  # Port on which the server will listen. the server binding is 0.0.0.0:{PORT}
  port: 5150
  # Binding for the server (which interface to bind to)
  binding: 0.0.0.0
  # The UI hostname or IP address that mailers will point to.
  host: http://localhost
  # Out of the box middleware configuration. to disable middleware you can changed the `enable` field to `false` of comment the middleware block
  middlewares:
    fallback:
      enable: false
    static:
      enable: true
      must_exist: true
      precompressed: false
      folder:
        uri: "/"
        path: "frontend/dist/frontend/browser"
      fallback: "frontend/dist/frontend/browser/index.html"

initializers:
  oauth2:
    secret_key: {{get_env(name="OAUTH_PRIVATE_KEY", default="144, 76, 183, 1, 15, 184, 233, 174, 214, 251, 190, 186, 122, 61, 74, 84, 225, 110, 189, 115, 10, 251, 133, 128, 52, 46, 15, 66, 85, 1, 245, 73, 27, 113, 189, 15, 209, 205, 61, 100, 73, 31, 18, 58, 235, 105, 141, 36, 70, 92, 231, 151, 27, 32, 243, 117, 30, 244, 110, 89, 233, 196, 137, 130")}} # Optional, key for Private Cookie Jar, must be more than 64 bytes
    authorization_code: # Authorization code grant type
      - client_identifier: authentik
        client_credentials:
          client_id: {{get_env(name="OAUTH_CLIENT_ID", default="workspace-booking")}} # Replace with your OAuth2 client ID.
          client_secret: {{get_env(name="OAUTH_CLIENT_SECRET", default="2shYGe1OXfO2wBDJA5OD6dB29U8UVdWhHzp4N4xFiqilQ9y7Z4HzUEHXaTBWbOTV9b3HeiNk1IGHghi1f1tkr8oGmR2HexUUnDPIWtZQiMHrAkPehtRC3B84UdMaUizT")}} # Replace with your OAuth2 client secret.
          auth_type: basic
        url_config:
          auth_url: {{get_env(name="AUTH_URL", default="http://localhost:9000/application/o/authorize/")}} # authorization endpoint from the provider
          token_url: {{get_env(name="TOKEN_URL", default="http://localhost:9000/application/o/token/")}} # token endpoint from the provider for exchanging the authorization code for an access token
          redirect_url: {{get_env(name="REDIRECT_URL", default="http://localhost:5150/api/oauth2/authentik/callback/cookie")}}
          profile_url: {{get_env(name="PROFILE_URL", default="http://localhost:9000/application/o/userinfo/")}} # user profile endpoint from the provider for getting user data
          scopes:
            - openid
            - email
            - profile
        cookie_config:
          protected_url: {{get_env(name="PROTECTED_URL", default="http://localhost:5150/")}} # Optional for jwt - For redirecting to protect url in cookie to prevent XSS attack
          cookie_secure: true
          cookie_path: "/"
          cookie_domain: "planner.verbis.dkfz.de"
          cookie_same_site: Lax
        timeout_seconds: 600 # Optional, default 600 seconds
  axum_session:
    cookie_config:
      cookie_secure: true
      cookie_path: "/"
      cookie_domain: "planner.verbis.dkfz.de"
      cookie_same_site: Lax

# Database Configuration
database:
  # Database connection URI
  uri: {{ get_env(name="DATABASE_URL", default="") }}
  # When enabled, the sql query will be logged.
  enable_logging: false
  # Set the timeout duration when acquiring a connection.
  connect_timeout: {{ get_env(name="DB_CONNECT_TIMEOUT", default="500") }}
  # Set the idle duration before closing a connection.
  idle_timeout: {{ get_env(name="DB_IDLE_TIMEOUT", default="500") }}
  # Minimum number of connections for a pool.
  min_connections: {{ get_env(name="DB_MIN_CONNECTIONS", default="1") }}
  # Maximum number of connections for a pool.
  max_connections: {{ get_env(name="DB_MAX_CONNECTIONS", default="5") }}
  # Run migration up when application loaded
  auto_migrate: true
  # Truncate database when application loaded. This is a dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_truncate: false
  # Recreating schema when application loaded.  This is a dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_recreate: false

# Authentication Configuration
auth:
  # JWT authentication
  jwt:
    # Secret key for token generation and verification
    secret: {{get_env(name="JWT_SECRET", default="ksF7UxOeIIZdk0b03VJE")}}
    # Token expiration time in seconds
    expiration: 604800 # 7 days
