name: Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        run: |
          docker build \
            --file Dockerfile \
            --tag workspace-booking-system:ci \
            .